Issue 54
plus3it/AMIgen7 pull request #57
Opened 2018-10-22 17:33 UTC by ferricoxide

Addresses issues encountered when attempting to use `t3` instance type for creating new "recovery" AMIs.

Also: adds documentation for using `register-image` for creating AMIs from EBS-snapshots (stripping `billingProduct` attribute from CentOS.Org-originated AMIs.

2018-10-22 18:53 UTC, lorengordon requested changes
Seems fine. Mostly just a couple suggestions/questions on the docs.

2018-10-22 18:53 UTC, lorengordon commented on Docs/README_register-image.md
> +In order to register an AMI that has been stripped of any `billibProduct` metadata, it will be necessary to register the image from an EBS snapshot. Registering from snapshot can be done either from
```suggestion
In order to register an AMI that has been stripped of any `billingProduct` metadata, it will be necessary to register the image from an EBS snapshot. Registering from snapshot can be done either from the EC2 Web Console or the AWS CLI. However, in order to ensure that support for ENA and SRIOV is enabled within the registered image, the AWS CLI must be used.
```

2018-10-22 18:53 UTC, lorengordon commented on register-image.md
> +Creating an AMI stripped of any `billingProduct` metadata requires using the [`register-image`](https://docs.aws.amazon.com/cli/latest/reference/ec2/register-image.html) method. While the _basics_ of
Is this doc a duplicate of README_register-image.md?

2018-10-23 13:19 UTC, ferricoxide commented on register-image.md
> +Creating an AMI stripped of any `billingProduct` metadata requires using the [`register-image`](https://docs.aws.amazon.com/cli/latest/reference/ec2/register-image.html) method. While the _basics_ of
goddammit... that file's not supposed to be there at all. I'd done a `git mv`, at one point, to make the file name line up with the other `Docs` directory contents.

2018-10-23 14:15 UTC, lorengordon approved these changes
Looks good to me, merge it if done!

2018-10-23 14:34 UTC, merged